- name: variables passing
  hosts: web
  vars:
   NAME: Bharath
   ADDRESS: Hyderabad
   MOBILE: 123456789
  tasks:
  - name: variables passing
    ansible.builtin.debug:
     msg: "I am {{NAME}}, my address {{ADDRESS}}, my mobile no {{MOBILE}}"
  - name: variables passing
    vars:
     NAME: kumar
     ADDRESS: amberpet
     MOBILE: 987654321
    ansible.builtin.debug:
     msg: "I am {{NAME}}, my address {{ADDRESS}}, my mobile no {{MOBILE}}"