- name: variables passing
  hosts: web
  vars_prompt:
   name: NAME
   prompt: please enter the name
   name: ADDRESS
   prompt: please enter the address
   name: MOBILE
   prompt: please enter the MOBILE
  tasks:
  - name: variables passing
    ansible.builtin.debug:
     msg: "I am {{NAME}}, my address {{ADDRESS}}, my mobile no: {{MOBILE}}"