- name: Data Types
  hosts: web
  vars:
   course: AWS Devops
   duration: 120
   topics:
    - ansible
    - git
    - shell script
    - dockers
   live: true
   tools:
    ci: jenkins
    cm: ansible
    cloud: aws
    tools:
     - ec2
     - iam
     - s3
  tasks:
   - name: Data Types
     ansible.builtin.debug:
      msg: "Hi, I am learning {{ course }}, with duration: {{ duration }}, topics are: {{ topics }}, and live: {{ live }}, tools are: {{ tools }}"