- name: Data Types
  hosts: web
  vars:
   course: AWS Devops
   duration: 120
   topics:
    - ansible
    - git
    - shell script
    - dockers
   live: true
   tools:
    - ec2
    - s3
    - IAM
  tasks:
   - name: Data Types
     ansible.builtin.debug:
      msg: "Hi, I am learning {{ course }}, with duration: {{ duration }}, topics are: {{ topics }}, and live: {{ live }}, tools are: {{ tools }}"