- name: loops demo
  hosts: web
  tasks: 
   - name: loops demo
     ansible.builtin.package:
      name: "{{ item }}""
      state: present
     loop:
     - nginx
     - mysql
     - httpd
     - postfix
     