- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: default variables
    ansible.builtin.debug:
     msg: "hello {{ NAME | default('Bharath')}}"

  - name: upper case
    ansible.builtin.debug:
     msg: "hello {{ 'bharath' | upper }}"

  - name: lower case
    ansible.builtin.debug:
     msg: "hello {{ 'BHARATH' | lower }}"

  - name: get the unique values
    vars:
      NUMBER: [1,2,3,4,4,5,5,6,7,7]
    ansible.builtin.debug:
     msg: "hello {{ NUMBER | unique }}"


 