- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: default variables
    ansible.builtin.debug:
     msg: "hello {{ NAME | default('Bharath')}}"

  - name: upper case
    ansible.builtin.debug:
     msg: "hello {{ 'bharath' | upper }}"

  - name: lower case
    ansible.builtin.debug:
     msg: "hello {{ 'BHARATH' | lower }}"

  - name: get the unique values
    vars:
      NUMBER: [1,2,3,4,4,5,5,6,7,7]
    ansible.builtin.debug:
     msg: "the unique values is : {{ NUMBER | unique }}"

  - name: get the min and max 
    vars:
      NUMBER: [1,2,3,4,44,5,55,6,77,7]
    ansible.builtin.debug:
     msg: "the max value is : {{ NUMBER | max }}, the min value is : {{ NUMBER | min }}"

  - name: convert Map to List
    vars:
     Info:
      NAME: Bharath
      ADRRESS: Hydetabad
    ansible.builtin.debug:
     msg: "{{ Info | dict2items }}"

  - name: convert List to Map
    vars:
     Info:
     - { "Key": "Name","value": "Bharath" }
     - { "key": "Address","value": "Hydetabad" }
     - { "key": "Course","value": "DevOps with AWS" }
    ansible.builtin.debug:
     msg: "{{ Info | items2dict }}"

 